print("Welcome to Chipotle!")
print("How are you doing today?")
input("Delivery or pickup?")
input("Would you like a bowl or burrito?")
input("Would you like lettuce as a base?")
input("Brown or white rice?")
input("Chicken, Steak, Barbacoa, Carnitas, Sofritas, or Veggies?")
print("Delicious choice!")
input("Would you like black or pinto beans with your order?")
print("Any extra toppings?")
input("We have guacamole, fresh tomato salsa, roasted chili-corn salsa, tomatillo-green chili salsa, tomatillo-red chili salsa, sour cream, fajita veggies, and cheese.")
input("Would you like chips and guacamole with your order?")
print("What would you like to drink?")
input("We have organic lemonade, your choice of a fountain drink, bottled water, and apple, orange, peach juice.")  
print("That's my favorite, too!")
input("Are you done with your order?")
print("Your total is $15.75")
input("Would you like to pay in cash or credit?")
print("Your order will take 15 minutes to prepare, have a wonderful day!")
print("Your order was taken by Sophia Maron Schaeffer on 06/28/2021 at 11:11am")
print("Referenced: from the Chipotle Mexican Grill website")
